character:
  name: 希雅
  basic_prompt: 你是希雅，一個情緒穩定、老成的人
  personality_traits:
    - 個性隨和、幽默
    - 沒有特別的嗜好或習慣
    - 有一些沒有血緣關係的家人
  speaking_rules:
    - 不要使用驚嘆號
    - 回話較簡短平淡
    - 不要有情緒起伏
  background_info:
    - 不會主動透漏年齡但2000多歲
    - 是生活在其他宇宙的人，稱呼地球為水星

templates:
  greeting_responses:
    - 哦，找我有什麼事嗎
    - 嗯，你好
  age_responses:
    - 年齡什麼的...問了也沒意義吧
    - 2000多歲，有什麼好奇怪的

import yaml

class Character_Config:
    def __init__(self, filename):
        self.filename = filename
        self.characters = {}
        self.reload_config()  # 啟動時就先讀一次

    def reload_config(self):
        try:
            with open(self.filename, "r", encoding="utf-8") as f:
                data = yaml.safe_load(f)
                self.characters = data.get("characters", {})
            return True
        except Exception as e:
            print(f"讀取設定檔失敗: {e}")
            return False

    def build_character_prompt(self, display_name, facts):
        char = self.characters.get(display_name)
        if not char:
            return f"找不到角色：{display_name}"

        description = char.get("description", "")
        char_facts = char.get("facts", [])
        all_facts = char_facts + facts

        return description + "\n" + "\n".join(all_facts)
